name: build-and-test
run-name: Build and test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Restore build cache
        id: build-cache-restore
        continue-on-error: true
        uses: actions/cache/restore@v3
        with:
          path: cache
          key: ${{ hashFiles('cache/**') }}
      - name: Build
        run: make
      - name: Save build cache
        id: build-cache-save
        uses: actions/cache/save@v3
        with:
          path: cache
          key: ${{ steps.build-cache-restore.outputs.cache-primary-key }}
      - name: Cache Docker environment
        if: always()
        run: make push
