name: build-and-test
run-name: Build and test
on: [push]
jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build
        run: make
      - name: Cache
        run: make push
